// flow-typed signature: ea8a9df88bef7eb99196ee1b4b660436
// flow-typed version: 0.15.2

// This is an autogenerated libdef stub for the 'ava' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'ava' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'ava' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'ava/api' {
  declare module.exports: any;
}

declare module 'ava/cli' {
  declare module.exports: any;
}

declare module 'ava/index' {
  declare module.exports: any;
}

declare module 'ava/lib/assert' {
  declare module.exports: any;
}

declare module 'ava/lib/ava-error' {
  declare module.exports: any;
}

declare module 'ava/lib/ava-files' {
  declare module.exports: any;
}

declare module 'ava/lib/beautify-stack' {
  declare module.exports: any;
}

declare module 'ava/lib/caching-precompiler' {
  declare module.exports: any;
}

declare module 'ava/lib/colors' {
  declare module.exports: any;
}

declare module 'ava/lib/concurrent' {
  declare module.exports: any;
}

declare module 'ava/lib/enhance-assert' {
  declare module.exports: any;
}

declare module 'ava/lib/fork' {
  declare module.exports: any;
}

declare module 'ava/lib/globals' {
  declare module.exports: any;
}

declare module 'ava/lib/hook' {
  declare module.exports: any;
}

declare module 'ava/lib/logger' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/mini' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/tap' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/verbose' {
  declare module.exports: any;
}

declare module 'ava/lib/run-status' {
  declare module.exports: any;
}

declare module 'ava/lib/runner' {
  declare module.exports: any;
}

declare module 'ava/lib/send' {
  declare module.exports: any;
}

declare module 'ava/lib/sequence' {
  declare module.exports: any;
}

declare module 'ava/lib/serialize-error' {
  declare module.exports: any;
}

declare module 'ava/lib/test-collection' {
  declare module.exports: any;
}

declare module 'ava/lib/test-worker' {
  declare module.exports: any;
}

declare module 'ava/lib/test' {
  declare module.exports: any;
}

declare module 'ava/lib/throws-helper' {
  declare module.exports: any;
}

declare module 'ava/lib/watcher' {
  declare module.exports: any;
}

declare module 'ava/profile' {
  declare module.exports: any;
}

