// flow-typed signature: 20de11517a694d80e437a8989c2a08dd
// flow-typed version: 3.4.6

// This is an autogenerated libdef stub for the 'bluebird' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'bluebird' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'bluebird' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'bluebird/js/browser/bluebird.core' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird.core.min' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird.min' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/any' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/assert' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/async' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/bind' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/bluebird' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/call_get' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/cancel' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/catch_filter' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/context' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/debuggability' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/direct_resolve' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/each' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/errors' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/es5' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/filter' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/finally' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/generators' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/join' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/map' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/method' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/nodeback' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/nodeify' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/promise_array' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/promise' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/promisify' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/props' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/queue' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/race' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/reduce' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/schedule' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/settle' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/some' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/synchronous_inspection' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/thenables' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/timers' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/using' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/util' {
  declare module.exports: any;
}

