// flow-typed signature: 30b8815fc0c900e2aab05ded9a0e468e
// flow-typed version: 0.0.1

// This is an autogenerated libdef stub for the 'deep-freeze' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'deep-freeze' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'deep-freeze' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'deep-freeze/example/deep' {
  declare module.exports: any;
}

declare module 'deep-freeze/index' {
  declare module.exports: any;
}

declare module 'deep-freeze/test/deep' {
  declare module.exports: any;
}

