// flow-typed signature: a35f3a9d503ff63df641e6a1ffdcfda9
// flow-typed version: 3.1.0

// This is an autogenerated libdef stub for the 'es6-error' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'es6-error' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'es6-error' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'es6-error/lib/index' {
  declare module.exports: any;
}

declare module 'es6-error/src/index' {
  declare module.exports: any;
}

declare module 'es6-error/test/index' {
  declare module.exports: any;
}

