// flow-typed signature: a1ffe1653066af455b6b98feddb256f4
// flow-typed version: 1.17.6

// This is an autogenerated libdef stub for the 'sinon' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'sinon' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'sinon' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'sinon/lib/sinon' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/assert' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/behavior' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/call' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/collection' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/extend' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/format' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/log_error' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/match' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/mock' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/sandbox' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/spy' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/stub' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/test_case' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/test' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/times_in_words' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/typeOf' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/core' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/event' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_server_with_clock' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_server' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_timers' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_xdomain_request' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/fake_xml_http_request' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/timers_ie' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/xdr_ie' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/util/xhr_ie' {
  declare module.exports: any;
}

declare module 'sinon/lib/sinon/walk' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-1.17.6' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-ie-1.17.6' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-ie' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-server-1.17.6' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon-server' {
  declare module.exports: any;
}

declare module 'sinon/pkg/sinon' {
  declare module.exports: any;
}

