// flow-typed signature: 56332df0dd73769264edd7e6536a4eb5
// flow-typed version: 5.7.0

// This is an autogenerated libdef stub for the 'validator' package.
// Feel free to leave it alone or fill it out as you need.
// If you do fill it out, we encourage you to share it with the community!
// Send pull requests to https://github.com/flowtype/flow-typed
declare module 'validator' {
  declare module.exports: any;
}

// These are stubs for each file inside the 'validator' package. They are
// included in case you need to require them directly. Feel free to delete them
// if you don't need them!
declare module 'validator/index' {
  declare module.exports: any;
}

declare module 'validator/lib/alpha' {
  declare module.exports: any;
}

declare module 'validator/lib/blacklist' {
  declare module.exports: any;
}

declare module 'validator/lib/contains' {
  declare module.exports: any;
}

declare module 'validator/lib/equals' {
  declare module.exports: any;
}

declare module 'validator/lib/escape' {
  declare module.exports: any;
}

declare module 'validator/lib/isAfter' {
  declare module.exports: any;
}

declare module 'validator/lib/isAlpha' {
  declare module.exports: any;
}

declare module 'validator/lib/isAlphanumeric' {
  declare module.exports: any;
}

declare module 'validator/lib/isAscii' {
  declare module.exports: any;
}

declare module 'validator/lib/isBase64' {
  declare module.exports: any;
}

declare module 'validator/lib/isBefore' {
  declare module.exports: any;
}

declare module 'validator/lib/isBoolean' {
  declare module.exports: any;
}

declare module 'validator/lib/isByteLength' {
  declare module.exports: any;
}

declare module 'validator/lib/isCreditCard' {
  declare module.exports: any;
}

declare module 'validator/lib/isCurrency' {
  declare module.exports: any;
}

declare module 'validator/lib/isDataURI' {
  declare module.exports: any;
}

declare module 'validator/lib/isDate' {
  declare module.exports: any;
}

declare module 'validator/lib/isDecimal' {
  declare module.exports: any;
}

declare module 'validator/lib/isDivisibleBy' {
  declare module.exports: any;
}

declare module 'validator/lib/isEmail' {
  declare module.exports: any;
}

declare module 'validator/lib/isFloat' {
  declare module.exports: any;
}

declare module 'validator/lib/isFQDN' {
  declare module.exports: any;
}

declare module 'validator/lib/isFullWidth' {
  declare module.exports: any;
}

declare module 'validator/lib/isHalfWidth' {
  declare module.exports: any;
}

declare module 'validator/lib/isHexadecimal' {
  declare module.exports: any;
}

declare module 'validator/lib/isHexColor' {
  declare module.exports: any;
}

declare module 'validator/lib/isIn' {
  declare module.exports: any;
}

declare module 'validator/lib/isInt' {
  declare module.exports: any;
}

declare module 'validator/lib/isIP' {
  declare module.exports: any;
}

declare module 'validator/lib/isISBN' {
  declare module.exports: any;
}

declare module 'validator/lib/isISIN' {
  declare module.exports: any;
}

declare module 'validator/lib/isISO8601' {
  declare module.exports: any;
}

declare module 'validator/lib/isJSON' {
  declare module.exports: any;
}

declare module 'validator/lib/isLength' {
  declare module.exports: any;
}

declare module 'validator/lib/isLowercase' {
  declare module.exports: any;
}

declare module 'validator/lib/isMACAddress' {
  declare module.exports: any;
}

declare module 'validator/lib/isMD5' {
  declare module.exports: any;
}

declare module 'validator/lib/isMobilePhone' {
  declare module.exports: any;
}

declare module 'validator/lib/isMongoId' {
  declare module.exports: any;
}

declare module 'validator/lib/isMultibyte' {
  declare module.exports: any;
}

declare module 'validator/lib/isNull' {
  declare module.exports: any;
}

declare module 'validator/lib/isNumeric' {
  declare module.exports: any;
}

declare module 'validator/lib/isSurrogatePair' {
  declare module.exports: any;
}

declare module 'validator/lib/isUppercase' {
  declare module.exports: any;
}

declare module 'validator/lib/isURL' {
  declare module.exports: any;
}

declare module 'validator/lib/isUUID' {
  declare module.exports: any;
}

declare module 'validator/lib/isVariableWidth' {
  declare module.exports: any;
}

declare module 'validator/lib/isWhitelisted' {
  declare module.exports: any;
}

declare module 'validator/lib/ltrim' {
  declare module.exports: any;
}

declare module 'validator/lib/matches' {
  declare module.exports: any;
}

declare module 'validator/lib/normalizeEmail' {
  declare module.exports: any;
}

declare module 'validator/lib/rtrim' {
  declare module.exports: any;
}

declare module 'validator/lib/stripLow' {
  declare module.exports: any;
}

declare module 'validator/lib/toBoolean' {
  declare module.exports: any;
}

declare module 'validator/lib/toDate' {
  declare module.exports: any;
}

declare module 'validator/lib/toFloat' {
  declare module.exports: any;
}

declare module 'validator/lib/toInt' {
  declare module.exports: any;
}

declare module 'validator/lib/trim' {
  declare module.exports: any;
}

declare module 'validator/lib/unescape' {
  declare module.exports: any;
}

declare module 'validator/lib/util/assertString' {
  declare module.exports: any;
}

declare module 'validator/lib/util/merge' {
  declare module.exports: any;
}

declare module 'validator/lib/util/toString' {
  declare module.exports: any;
}

declare module 'validator/lib/whitelist' {
  declare module.exports: any;
}

declare module 'validator/validator' {
  declare module.exports: any;
}

declare module 'validator/validator.min' {
  declare module.exports: any;
}

